// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: vdevice/v1/vdevice.proto

package vdevicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyAction int32

const (
	KeyAction_KEY_ACTION_UNSPECIFIED KeyAction = 0
	KeyAction_KEY_PRESS              KeyAction = 1
	KeyAction_KEY_DOWN               KeyAction = 2
	KeyAction_KEY_UP                 KeyAction = 3
)

// Enum value maps for KeyAction.
var (
	KeyAction_name = map[int32]string{
		0: "KEY_ACTION_UNSPECIFIED",
		1: "KEY_PRESS",
		2: "KEY_DOWN",
		3: "KEY_UP",
	}
	KeyAction_value = map[string]int32{
		"KEY_ACTION_UNSPECIFIED": 0,
		"KEY_PRESS":              1,
		"KEY_DOWN":               2,
		"KEY_UP":                 3,
	}
)

func (x KeyAction) Enum() *KeyAction {
	p := new(KeyAction)
	*p = x
	return p
}

func (x KeyAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyAction) Descriptor() protoreflect.EnumDescriptor {
	return file_vdevice_v1_vdevice_proto_enumTypes[0].Descriptor()
}

func (KeyAction) Type() protoreflect.EnumType {
	return &file_vdevice_v1_vdevice_proto_enumTypes[0]
}

func (x KeyAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyAction.Descriptor instead.
func (KeyAction) EnumDescriptor() ([]byte, []int) {
	return file_vdevice_v1_vdevice_proto_rawDescGZIP(), []int{0}
}

type MouseAction int32

const (
	MouseAction_MOUSE_ACTION_UNSPECIFIED MouseAction = 0
	MouseAction_MOUSE_MOVE_LEFT          MouseAction = 1
	MouseAction_MOUSE_MOVE_RIGHT         MouseAction = 2
	MouseAction_MOUSE_MOVE_UP            MouseAction = 3
	MouseAction_MOUSE_MOVE_DOWN          MouseAction = 4
	MouseAction_MOUSE_MOVE               MouseAction = 5
	MouseAction_MOUSE_LEFT_CLICK         MouseAction = 6
	MouseAction_MOUSE_RIGHT_CLICK        MouseAction = 7
	MouseAction_MOUSE_MIDDLE_CLICK       MouseAction = 8
	MouseAction_MOUSE_LEFT_PRESS         MouseAction = 9
	MouseAction_MOUSE_LEFT_RELEASE       MouseAction = 10
	MouseAction_MOUSE_RIGHT_PRESS        MouseAction = 11
	MouseAction_MOUSE_RIGHT_RELEASE      MouseAction = 12
	MouseAction_MOUSE_MIDDLE_PRESS       MouseAction = 13
	MouseAction_MOUSE_MIDDLE_RELEASE     MouseAction = 14
	MouseAction_MOUSE_WHEEL              MouseAction = 15
)

// Enum value maps for MouseAction.
var (
	MouseAction_name = map[int32]string{
		0:  "MOUSE_ACTION_UNSPECIFIED",
		1:  "MOUSE_MOVE_LEFT",
		2:  "MOUSE_MOVE_RIGHT",
		3:  "MOUSE_MOVE_UP",
		4:  "MOUSE_MOVE_DOWN",
		5:  "MOUSE_MOVE",
		6:  "MOUSE_LEFT_CLICK",
		7:  "MOUSE_RIGHT_CLICK",
		8:  "MOUSE_MIDDLE_CLICK",
		9:  "MOUSE_LEFT_PRESS",
		10: "MOUSE_LEFT_RELEASE",
		11: "MOUSE_RIGHT_PRESS",
		12: "MOUSE_RIGHT_RELEASE",
		13: "MOUSE_MIDDLE_PRESS",
		14: "MOUSE_MIDDLE_RELEASE",
		15: "MOUSE_WHEEL",
	}
	MouseAction_value = map[string]int32{
		"MOUSE_ACTION_UNSPECIFIED": 0,
		"MOUSE_MOVE_LEFT":          1,
		"MOUSE_MOVE_RIGHT":         2,
		"MOUSE_MOVE_UP":            3,
		"MOUSE_MOVE_DOWN":          4,
		"MOUSE_MOVE":               5,
		"MOUSE_LEFT_CLICK":         6,
		"MOUSE_RIGHT_CLICK":        7,
		"MOUSE_MIDDLE_CLICK":       8,
		"MOUSE_LEFT_PRESS":         9,
		"MOUSE_LEFT_RELEASE":       10,
		"MOUSE_RIGHT_PRESS":        11,
		"MOUSE_RIGHT_RELEASE":      12,
		"MOUSE_MIDDLE_PRESS":       13,
		"MOUSE_MIDDLE_RELEASE":     14,
		"MOUSE_WHEEL":              15,
	}
)

func (x MouseAction) Enum() *MouseAction {
	p := new(MouseAction)
	*p = x
	return p
}

func (x MouseAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MouseAction) Descriptor() protoreflect.EnumDescriptor {
	return file_vdevice_v1_vdevice_proto_enumTypes[1].Descriptor()
}

func (MouseAction) Type() protoreflect.EnumType {
	return &file_vdevice_v1_vdevice_proto_enumTypes[1]
}

func (x MouseAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MouseAction.Descriptor instead.
func (MouseAction) EnumDescriptor() ([]byte, []int) {
	return file_vdevice_v1_vdevice_proto_rawDescGZIP(), []int{1}
}

type KeyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        KeyAction              `protobuf:"varint,1,opt,name=action,proto3,enum=vdevice.v1.KeyAction" json:"action,omitempty"`
	KeyCode       uint32                 `protobuf:"varint,2,opt,name=key_code,json=keyCode,proto3" json:"key_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEvent) Reset() {
	*x = KeyEvent{}
	mi := &file_vdevice_v1_vdevice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEvent) ProtoMessage() {}

func (x *KeyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vdevice_v1_vdevice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEvent.ProtoReflect.Descriptor instead.
func (*KeyEvent) Descriptor() ([]byte, []int) {
	return file_vdevice_v1_vdevice_proto_rawDescGZIP(), []int{0}
}

func (x *KeyEvent) GetAction() KeyAction {
	if x != nil {
		return x.Action
	}
	return KeyAction_KEY_ACTION_UNSPECIFIED
}

func (x *KeyEvent) GetKeyCode() uint32 {
	if x != nil {
		return x.KeyCode
	}
	return 0
}

type MouseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        MouseAction            `protobuf:"varint,1,opt,name=action,proto3,enum=vdevice.v1.MouseAction" json:"action,omitempty"`
	Pixel         int32                  `protobuf:"varint,2,opt,name=pixel,proto3" json:"pixel,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Horizontal    bool                   `protobuf:"varint,5,opt,name=horizontal,proto3" json:"horizontal,omitempty"`
	Delta         int32                  `protobuf:"varint,6,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MouseEvent) Reset() {
	*x = MouseEvent{}
	mi := &file_vdevice_v1_vdevice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MouseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseEvent) ProtoMessage() {}

func (x *MouseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vdevice_v1_vdevice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseEvent.ProtoReflect.Descriptor instead.
func (*MouseEvent) Descriptor() ([]byte, []int) {
	return file_vdevice_v1_vdevice_proto_rawDescGZIP(), []int{1}
}

func (x *MouseEvent) GetAction() MouseAction {
	if x != nil {
		return x.Action
	}
	return MouseAction_MOUSE_ACTION_UNSPECIFIED
}

func (x *MouseEvent) GetPixel() int32 {
	if x != nil {
		return x.Pixel
	}
	return 0
}

func (x *MouseEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MouseEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MouseEvent) GetHorizontal() bool {
	if x != nil {
		return x.Horizontal
	}
	return false
}

func (x *MouseEvent) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

var File_vdevice_v1_vdevice_proto protoreflect.FileDescriptor

const file_vdevice_v1_vdevice_proto_rawDesc = "" +
	"\n" +
	"\x18vdevice/v1/vdevice.proto\x12\n" +
	"vdevice.v1\x1a\x1bgoogle/protobuf/empty.proto\"T\n" +
	"\bKeyEvent\x12-\n" +
	"\x06action\x18\x01 \x01(\x0e2\x15.vdevice.v1.KeyActionR\x06action\x12\x19\n" +
	"\bkey_code\x18\x02 \x01(\rR\akeyCode\"\xa5\x01\n" +
	"\n" +
	"MouseEvent\x12/\n" +
	"\x06action\x18\x01 \x01(\x0e2\x17.vdevice.v1.MouseActionR\x06action\x12\x14\n" +
	"\x05pixel\x18\x02 \x01(\x05R\x05pixel\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x1e\n" +
	"\n" +
	"horizontal\x18\x05 \x01(\bR\n" +
	"horizontal\x12\x14\n" +
	"\x05delta\x18\x06 \x01(\x05R\x05delta*P\n" +
	"\tKeyAction\x12\x1a\n" +
	"\x16KEY_ACTION_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tKEY_PRESS\x10\x01\x12\f\n" +
	"\bKEY_DOWN\x10\x02\x12\n" +
	"\n" +
	"\x06KEY_UP\x10\x03*\xf4\x02\n" +
	"\vMouseAction\x12\x1c\n" +
	"\x18MOUSE_ACTION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fMOUSE_MOVE_LEFT\x10\x01\x12\x14\n" +
	"\x10MOUSE_MOVE_RIGHT\x10\x02\x12\x11\n" +
	"\rMOUSE_MOVE_UP\x10\x03\x12\x13\n" +
	"\x0fMOUSE_MOVE_DOWN\x10\x04\x12\x0e\n" +
	"\n" +
	"MOUSE_MOVE\x10\x05\x12\x14\n" +
	"\x10MOUSE_LEFT_CLICK\x10\x06\x12\x15\n" +
	"\x11MOUSE_RIGHT_CLICK\x10\a\x12\x16\n" +
	"\x12MOUSE_MIDDLE_CLICK\x10\b\x12\x14\n" +
	"\x10MOUSE_LEFT_PRESS\x10\t\x12\x16\n" +
	"\x12MOUSE_LEFT_RELEASE\x10\n" +
	"\x12\x15\n" +
	"\x11MOUSE_RIGHT_PRESS\x10\v\x12\x17\n" +
	"\x13MOUSE_RIGHT_RELEASE\x10\f\x12\x16\n" +
	"\x12MOUSE_MIDDLE_PRESS\x10\r\x12\x18\n" +
	"\x14MOUSE_MIDDLE_RELEASE\x10\x0e\x12\x0f\n" +
	"\vMOUSE_WHEEL\x10\x0f2J\n" +
	"\x0fKeyboardService\x127\n" +
	"\aSendKey\x12\x14.vdevice.v1.KeyEvent\x1a\x16.google.protobuf.Empty2J\n" +
	"\fMouseService\x12:\n" +
	"\bUseMouse\x12\x16.vdevice.v1.MouseEvent\x1a\x16.google.protobuf.EmptyB?Z=github.com/roshsyed/virtinput-server/api/vdevice/v1;vdevicev1b\x06proto3"

var (
	file_vdevice_v1_vdevice_proto_rawDescOnce sync.Once
	file_vdevice_v1_vdevice_proto_rawDescData []byte
)

func file_vdevice_v1_vdevice_proto_rawDescGZIP() []byte {
	file_vdevice_v1_vdevice_proto_rawDescOnce.Do(func() {
		file_vdevice_v1_vdevice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vdevice_v1_vdevice_proto_rawDesc), len(file_vdevice_v1_vdevice_proto_rawDesc)))
	})
	return file_vdevice_v1_vdevice_proto_rawDescData
}

var file_vdevice_v1_vdevice_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_vdevice_v1_vdevice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vdevice_v1_vdevice_proto_goTypes = []any{
	(KeyAction)(0),        // 0: vdevice.v1.KeyAction
	(MouseAction)(0),      // 1: vdevice.v1.MouseAction
	(*KeyEvent)(nil),      // 2: vdevice.v1.KeyEvent
	(*MouseEvent)(nil),    // 3: vdevice.v1.MouseEvent
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_vdevice_v1_vdevice_proto_depIdxs = []int32{
	0, // 0: vdevice.v1.KeyEvent.action:type_name -> vdevice.v1.KeyAction
	1, // 1: vdevice.v1.MouseEvent.action:type_name -> vdevice.v1.MouseAction
	2, // 2: vdevice.v1.KeyboardService.SendKey:input_type -> vdevice.v1.KeyEvent
	3, // 3: vdevice.v1.MouseService.UseMouse:input_type -> vdevice.v1.MouseEvent
	4, // 4: vdevice.v1.KeyboardService.SendKey:output_type -> google.protobuf.Empty
	4, // 5: vdevice.v1.MouseService.UseMouse:output_type -> google.protobuf.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vdevice_v1_vdevice_proto_init() }
func file_vdevice_v1_vdevice_proto_init() {
	if File_vdevice_v1_vdevice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vdevice_v1_vdevice_proto_rawDesc), len(file_vdevice_v1_vdevice_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_vdevice_v1_vdevice_proto_goTypes,
		DependencyIndexes: file_vdevice_v1_vdevice_proto_depIdxs,
		EnumInfos:         file_vdevice_v1_vdevice_proto_enumTypes,
		MessageInfos:      file_vdevice_v1_vdevice_proto_msgTypes,
	}.Build()
	File_vdevice_v1_vdevice_proto = out.File
	file_vdevice_v1_vdevice_proto_goTypes = nil
	file_vdevice_v1_vdevice_proto_depIdxs = nil
}
