// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: vdevice/v1/vdevice.proto

package vdevicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyboardService_SendKey_FullMethodName = "/vdevice.v1.KeyboardService/SendKey"
)

// KeyboardServiceClient is the client API for KeyboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyboardServiceClient interface {
	SendKey(ctx context.Context, in *KeyEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type keyboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyboardServiceClient(cc grpc.ClientConnInterface) KeyboardServiceClient {
	return &keyboardServiceClient{cc}
}

func (c *keyboardServiceClient) SendKey(ctx context.Context, in *KeyEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KeyboardService_SendKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyboardServiceServer is the server API for KeyboardService service.
// All implementations must embed UnimplementedKeyboardServiceServer
// for forward compatibility.
type KeyboardServiceServer interface {
	SendKey(context.Context, *KeyEvent) (*emptypb.Empty, error)
	mustEmbedUnimplementedKeyboardServiceServer()
}

// UnimplementedKeyboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyboardServiceServer struct{}

func (UnimplementedKeyboardServiceServer) SendKey(context.Context, *KeyEvent) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendKey not implemented")
}
func (UnimplementedKeyboardServiceServer) mustEmbedUnimplementedKeyboardServiceServer() {}
func (UnimplementedKeyboardServiceServer) testEmbeddedByValue()                         {}

// UnsafeKeyboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyboardServiceServer will
// result in compilation errors.
type UnsafeKeyboardServiceServer interface {
	mustEmbedUnimplementedKeyboardServiceServer()
}

func RegisterKeyboardServiceServer(s grpc.ServiceRegistrar, srv KeyboardServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyboardService_ServiceDesc, srv)
}

func _KeyboardService_SendKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyboardServiceServer).SendKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyboardService_SendKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyboardServiceServer).SendKey(ctx, req.(*KeyEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyboardService_ServiceDesc is the grpc.ServiceDesc for KeyboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vdevice.v1.KeyboardService",
	HandlerType: (*KeyboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendKey",
			Handler:    _KeyboardService_SendKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vdevice/v1/vdevice.proto",
}

const (
	MouseService_UseMouse_FullMethodName = "/vdevice.v1.MouseService/UseMouse"
)

// MouseServiceClient is the client API for MouseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MouseServiceClient interface {
	UseMouse(ctx context.Context, in *MouseEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type mouseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMouseServiceClient(cc grpc.ClientConnInterface) MouseServiceClient {
	return &mouseServiceClient{cc}
}

func (c *mouseServiceClient) UseMouse(ctx context.Context, in *MouseEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MouseService_UseMouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MouseServiceServer is the server API for MouseService service.
// All implementations must embed UnimplementedMouseServiceServer
// for forward compatibility.
type MouseServiceServer interface {
	UseMouse(context.Context, *MouseEvent) (*emptypb.Empty, error)
	mustEmbedUnimplementedMouseServiceServer()
}

// UnimplementedMouseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMouseServiceServer struct{}

func (UnimplementedMouseServiceServer) UseMouse(context.Context, *MouseEvent) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UseMouse not implemented")
}
func (UnimplementedMouseServiceServer) mustEmbedUnimplementedMouseServiceServer() {}
func (UnimplementedMouseServiceServer) testEmbeddedByValue()                      {}

// UnsafeMouseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MouseServiceServer will
// result in compilation errors.
type UnsafeMouseServiceServer interface {
	mustEmbedUnimplementedMouseServiceServer()
}

func RegisterMouseServiceServer(s grpc.ServiceRegistrar, srv MouseServiceServer) {
	// If the following call panics, it indicates UnimplementedMouseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MouseService_ServiceDesc, srv)
}

func _MouseService_UseMouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MouseEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MouseServiceServer).UseMouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MouseService_UseMouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MouseServiceServer).UseMouse(ctx, req.(*MouseEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// MouseService_ServiceDesc is the grpc.ServiceDesc for MouseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MouseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vdevice.v1.MouseService",
	HandlerType: (*MouseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UseMouse",
			Handler:    _MouseService_UseMouse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vdevice/v1/vdevice.proto",
}
